version: 2
tools:
  python-flake8: &python-flake8
    lint-command: 'flake8 --stdin-display-name ${INPUT} -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'

  python-yapf: &python-yapf
    format-command: 'yapf --quiet'
    format-stdin: true

languages:
  python:
    - <<: *python-flake8
    - <<: *python-yapf
