require('nvim-treesitter.configs').setup {
    ensure_installed = {
        'bash',
        'c',
        'cpp',
        'css',
        'dockerfile',
        'gitcommit',
        'gitignore',
        'go',
        'graphql',
        'html',
        'javascript',
        'jq',
        'json',
        'json5',
        'lua',
        'markdown',
        'markdown_inline',
        'php',
        'python',
        'regex',
        'ruby',
        'rust',
        'scala',
        'scss',
        'sql',
        'terraform',
        'tsx',
        'typescript',
        'vim',
        'vue',
        'yaml',
        'zig',
    },
    highlight = { enable = true, },
    autotag = { enable = true, },
    indent = { enable = true }
}
