import = ["~/.config/alacritty/themes/themes/tokyo-night.toml"]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 15

[font.bold]
family = "Hack Nerd Font Mono"
style = "Regular"

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 1

[[keyboard.bindings]]
chars = "\u0011"
key = "Q"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[32;2u"
key = "Space"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[32;5u"
key = "Space"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "b"
mods = "Alt|Control"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "f"
mods = "Alt|Control"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[window]
decorations = "buttonless"
dynamic_padding = true
opacity = 1.00
startup_mode = "Windowed"

[window.dimensions]
columns = 180
lines = 52

[window.padding]
x = 0
y = 0
